# Generated by Django 5.1.3 on 2024-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
                ("genre", models.CharField(max_length=100)),
                ("medium", models.CharField(max_length=100)),
                ("style", models.CharField(max_length=100)),
                ("created_year", models.IntegerField()),
            ],
        ),
    ]
