# Generated by Django 5.1.3 on 2024-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_artist_alter_artpiece_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="death_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="artists/"),
        ),
    ]
