# Generated by Django 5.1.3 on 2024-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_artist_death_date_alter_artist_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artpiece",
            name="image_url",
        ),
        migrations.AddField(
            model_name="artpiece",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="art_pieces/"),
        ),
    ]
