# Generated by Django 5.1.3 on 2024-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_remove_artpiece_image_url_artpiece_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="era",
            field=models.CharField(
                choices=[
                    ("Modern", "Modern"),
                    ("Contemporary", "Contemporary"),
                    ("Classical", "Classical"),
                    ("Renaissance", "Renaissance"),
                    ("Baroque", "Baroque"),
                ],
                default="Modern",
                max_length=50,
            ),
        ),
    ]
