# Generated by Django 5.1.3 on 2024-11-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_artist_era"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="artpiece",
            name="genre",
        ),
        migrations.AlterField(
            model_name="artist",
            name="era",
            field=models.CharField(
                choices=[
                    ("Modern", "Modern"),
                    ("Contemporary", "Contemporary"),
                    ("Classical", "Classical"),
                    ("Renaissance", "Renaissance"),
                    ("Baroque", "Baroque"),
                    ("Realism", "Realism"),
                ],
                default="Modern",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="artpiece",
            name="genres",
            field=models.ManyToManyField(related_name="art_pieces", to="gallery.genre"),
        ),
    ]
