# Generated by Django 5.1.3 on 2024-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_genre_remove_artpiece_genre_alter_artist_era_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="artpiece",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
