# Generated by Django 5.1.3 on 2024-12-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_artist_is_verified_artpiece_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="contributor_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
