# Generated by Django 5.1.3 on 2024-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_artist_contributor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpiece",
            name="contributor_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
