# Generated by Django 5.1.3 on 2024-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_alter_artpiece_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artpiece",
            name="genres",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="art_pieces", to="gallery.genre"
            ),
        ),
        migrations.AlterField(
            model_name="artpiece",
            name="medium",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="artpiece",
            name="style",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
