# Generated by Django 5.1.3 on 2024-12-01 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0012_alter_artpiece_genres_alter_artpiece_medium_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="added_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="artist",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Under Review", "Under Review"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="artpiece",
            name="added_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="artpiece",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Under Review", "Under Review"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
