# Generated by Django 5.1.3 on 2024-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gallery",
            "0013_artist_added_time_artist_status_artpiece_added_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="is_contributed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="artpiece",
            name="is_contributed",
            field=models.BooleanField(default=True),
        ),
    ]
